
from services.mcp.main import mcp

@mcp.resource("data://wide_reciever_strategy")
def wide_reciever_strategy() -> str:
    """Provides the application configuration."""
    return """
        # Common Terms and Abrreviations:
        - WR = Wide Receiver
    
        # Role Driven Evaluation:
        - Wide receivers emerge as fantasy assets through superior talent.

        # Skill-Based Evaluation:
        - Target Share (TGT%): ...
        - Snap Share (SNAP%): ...
        - Yards per Route Run (YPRR): ...

        # Context-Driven Evaluation:
        - Offensive Line Play: ...
        - Injuries: 
            - Injury to the starting quarterback will likely decrease the offensive's production, limiting the wide receiver's opportunities for touchdowns and rush attempts as the team will be in more passing situations.
        - Teammate Competition: 
            - A roster with multiple healthy, capable wide receivers is good to have, as it suggests the overall offense can be more productive.
        - Offensive Scheme: ...
        - Game Script: ...
        - Weather: ...

        # Positioning:
        - Slot: Increases opportunities for easy receptions, beneficial in PPR formats.
        - Outside: Increases chance for big plays and touchdowns, suffers from week to week variance.

        # Team Contenxt:
        - Wide receivers are less susceptible to flucations in offensive production, aside from poor QB play.

        # Types of Catch Opportunities:
        - Short Routes: ...
        - Middle Routes: ...
        - Deep Routes: ...
        - Screen Passes: ...
        - Bubble Screen Passes: ...
        - Screen Passes: ...
        - Screen Passes: ...

"""