version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./services/api/core/config.py:/app/config/config.py
    networks:
      - lox-network
    restart: unless-stopped
  mcp:
    build:
      context: .
      dockerfile: docker/Dockerfile.mcp
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./services/mcp/core/config.py:/app/config/config.py
    networks:
      - lox-network
    restart: unless-stopped
  ui:
    build:
      context: .
      dockerfile: docker/Dockerfile.ui
    ports:
      - "80:80"
    networks:
      - lox-network
    restart: unless-stopped

networks:
  lox-network:
    driver: bridge
