version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_KEY_PREFIX=thread
      - REDIS_TTL_SECONDS=2592000
    volumes:
      - ./services/api/core/config.py:/app/config/config.py
    networks:
      - lox-network
    depends_on:
      - redis
    restart: unless-stopped
  mcp:
    build:
      context: .
      dockerfile: docker/Dockerfile.mcp
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./services/mcp/core/config.py:/app/config/config.py
    networks:
      - lox-network
    depends_on:
      - redis
    restart: unless-stopped
  ui:
    build:
      context: .
      dockerfile: docker/Dockerfile.ui
    ports:
      - "80:80"
    networks:
      - lox-network
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - lox-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  redis_data:

networks:
  lox-network:
    driver: bridge
